---
- hosts: localhost
  become: yes
  tasks:
    - name: install epel package
      yum:
        name:
          - epel-release -y
          - wget
          - java-1.8.0-openjdk
    - name: install jenkins repo
      wget: -O /etc/yum.repos.d/jenkins.repo
        http://pkg.jenkins.io/redhat-stable/jenkins.repo
    - name: adding the key by using url
      rpm_key:
        state: present
        key: --import http://pkg.jenkins.io/redhat-stable/jenkins.io.key
        yum: 
        name: install jenkins -y
