---
- hosts: localhost
  become: yes
  tasks:
    - name: install java
      yum:
        name:
          - java-1.8.0-openjdk

    - name: download nexus
      get_url:
        url: https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-3.0.2-02-unix.tar.gz
        dest: /opt/nexus-3.0.2-02-unix.tar.gz
    - name: setting path
      file:
        path: /opt/nexus-3.0.2-02-unix
        state: directory
    - name: Unzip nexus
      unarchive:
        src: /opt/nexus-3.0.2-02-unix.tar.gz
        dest: /opt/nexus-3.0.2-02-unix
        copy: no
 

    - name: Add a line to a file if the file does not exist, without passing regexp
      lineinfile:
        path: /opt/nexus-3.0.2-02-unix/nexus-3.0.2-02/bin/nexus.rc
        line: run_as_user="centos"
        create: yes


    - name: Create a symbolic link
      file:
        src: /opt/nexus-3.0.2-02-unix/nexus-3.0.2-02/bin/nexus 
        dest: /etc/init.d/nexus 
        state: link 
    
    - name: start nexus server
      service:
        enabled: yes
        name: nexus
        state: started
     
          
    - name: adding the script file
      script: /home/centos/txt.sh args={executable=bash}
           
