---
- hosts: localhost
  become: yes
  tasks:
    - name: install java
      yum:
        name:
          - java-1.8.0-openjdk

    - name: "download the package by using url "
      get_url:
        url: https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-3.0.2-02-unix.tar.gz
        dest: /opt
        mode: "0755"

    - name: unzip the tar file
      unarchive:
        src: /opt/nexus-3.0.2-02-unix.tar.gz
        dest: /opt/nexus

    - name: Change file ownership, group and permissions
      file:
        path: /opt/nexus
        owner: centos
        group: centos
        mode: "0757"

    - name: Add a line to a file if the file does not exist, without passing regexp
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        line: run_as_user="centos"
        create: yes

    - name: start jenkins server when the server is booted
      service:
        enabled: yes
        name: nexus
        state: started
